export enum ActionType {
   EDIT_FORM_STATE="EDIT_FORM_STATE" ,
   CONTROL_NAME_STATE="CONTROL_NAME_STATE",
   UPDATE_EDIT_SCHEMA_BY_ID="UPDATE_EDIT_SCHEMA_BY_ID",
   CLEAN_DATASOURCE="CLEAN_DATASOURCE",
   CLEAN_REPORT="CLEAN_REPORT",
   ADD_DATASOURCE="ADD_DATASOURCE",
   ADD_REPORT="ADD_REPORT" 
,}